# Altere 'cardapio_db' para o nome que você quer dar ao seu banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/cardapio_db
spring.datasource.username=postgres
spring.datasource.password=32381108

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect